### ISSUE TITLE
required updates caused by repository ownership change and rename

### ISSUE THREAD

**Issue by jmMeessen** [jenkins-infra/jenkins-contribution-stats#71]
### What feature do you want to see added?

With the rename of the tooling used by this processing chain, several items must be corrected so that the daily and monthly processing continues to work

### Upstream changes

- https://github.com/jenkins-infra/jenkins-contribution-extractor/issues/47
- https://github.com/jenkins-infra/jenkins-contribution-aggregator/issues/37
```[tasklist]
### Tasks
- [x] replace all occurence of `jenkins-stats` with `jenkins-contribution-extractor` in scripts and documentation
- [x] replace all occurences of `jenkins-top-contributor` with `jenkins-contribution-aggregator` in scripts and documentation
- [x] check automatic updaters (dependabot/updateCLI)
- [x] Check docker image and automated run (GitHub action)
- [x] ask Jmm to remove old Brew Tap for full validation
- [x] Allow direct commit to main branch
```

**Comment by jmMeessen** [comment]
This issue can only be worked on once 
- [ ] `jenkins-contribution-extractor` is available with homebrew
- [ ] `jenkins-contribution-aggregator` is available with homebrew

**Comment by jmMeessen** [comment]
Looks completed. The next production run will confirm.
